service: bamboo-on-teams-${self:custom.version}

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  memorySize: 512
  region: ap-southeast-2
  stage: ${opt:stage, 'local'}
  timeout: 30

  deploymentBucket:
    name: ${ssm:/bamboo-on-teams/deploymentBucket}
    serverSideEncryption: AES256

  # VPC configuration for functions to access the private Bamboo API which can be removed if Bamboo is public available.
  vpc:
    securityGroupIds:
      - ${ssm:/bamboo-on-teams/securityGroupId}
    subnetIds:
      - ${ssm:/bamboo-on-teams/subnetId}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ssm:GetParameter
      Resource:
        - arn:aws:ssm:${self:provider.region}:${ssm:/bamboo-on-teams/accountId}:parameter/bamboo-on-teams/*
    - Effect: Allow
      Action:
        - states:StartExecution
      Resource:
        - ${self:custom.aws.stepFunction.statusChecker.arn}
        - ${self:custom.aws.stepFunction.buildAndDeployer.arn}
        - ${self:custom.aws.stepFunction.batcher.arn}
        - ${self:custom.aws.stepFunction.releaser.arn}

  apiGateway:
    restApiId: !Ref ApiGatewayRestApi
    restApiRootResourceId: !Ref bambooV1PathResource

  environment:
    REGION: ap-southeast-2
    BATH_PATH: bamboo/v1${self:custom.api.urls.prefix}
    STATUS_CHECKER_ARN: ${self:custom.aws.stepFunction.statusChecker.arn}
    BUILD_AND_DEPLOYER_ARN: ${self:custom.aws.stepFunction.buildAndDeployer.arn}
    BATCHER_ARN: ${self:custom.aws.stepFunction.batcher.arn}
    RELEASER_ARN: ${self:custom.aws.stepFunction.releaser.arn}
    STEP_FUNCTIONS_ENDPOINT: https://states.ap-southeast-2.amazonaws.com
    TZ: Pacific/Auckland
    APPLICATION_CONFIG: ${ssm:/bamboo-on-teams/applicationConfig~true}

package:
  excludeDevDependencies: false
  patterns:
    - '!node_modules/**'

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.aws.gateway.name}
        EndpointConfiguration:
          Types:
            - REGIONAL
        Policy:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: execute-api:Invoke
              Resource:
                - execute-api:/*/*/*

    BasePathResourse:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref ApiGatewayRestApi
        ParentId: !GetAtt
          - ApiGatewayRestApi
          - RootResourceId
        PathPart: bamboo

    bambooV1PathResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref ApiGatewayRestApi
        ParentId: !Ref BasePathResourse
        PathPart: v1

functions:
  api:
    name: ${self:service}
    events:
      - http:
          private: false
          path: ${self:custom.api.urls.command}
          method: post
          cors: true
    handler: dist/functions/api/router.router
  # release operation lambda
  notifyReleaseFunc:
    name: ${self:service}-${self:provider.stage}-notifyRelease
    handler: dist/functions/api/handlers/batcher.notifyRelease
  # batch operation lambdas
  executeSingleFunc:
    name: ${self:service}-${self:provider.stage}-executeSingle
    handler: dist/functions/api/handlers/batcher.executeSingle
  checkSingleFunc:
    name: ${self:service}-${self:provider.stage}-checkSingle
    handler: dist/functions/api/handlers/batcher.checkSingle
  notifySingleFunc:
    name: ${self:service}-${self:provider.stage}-notifySingle
    handler: dist/functions/api/handlers/batcher.notifySingle
  notifyAllFunc:
    name: ${self:service}-${self:provider.stage}-notifyAll
    handler: dist/functions/api/handlers/batcher.notifyAll
  # non batch operations lambdas
  checkStatusFunc:
    name: ${self:service}-${self:provider.stage}-statusChecker
    handler: dist/functions/api/handlers/statusChecker.checkJobStatus
  notifyStatusFunc:
    name: ${self:service}-${self:provider.stage}-statusNotifier
    handler: dist/functions/api/handlers/statusChecker.notifyJobStatus

plugins:
  - serverless-offline
  - serverless-offline-ssm
  - serverless-step-functions
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-prune-plugin

stepFunctions:
  stateMachines: ${file(resources/stateMachines.yml)}

custom:
  version: v1
  aws:
    gateway:
      name: ${self:service}
    stepFunction:
      releaser:
        name: ${self:service}-releaser-${self:provider.stage}
        arn: arn:aws:states:${self:provider.region}:${ssm:/bamboo-on-teams/accountId}:stateMachine:${self:custom.aws.stepFunction.releaser.name}
      batcher:
        name: ${self:service}-batcher-${self:provider.stage}
        arn: arn:aws:states:${self:provider.region}:${ssm:/bamboo-on-teams/accountId}:stateMachine:${self:custom.aws.stepFunction.batcher.name}
      buildAndDeployer:
        name: ${self:service}-build-and-deployer-${self:provider.stage}
        arn: arn:aws:states:${self:provider.region}:${ssm:/bamboo-on-teams/accountId}:stateMachine:${self:custom.aws.stepFunction.buildAndDeployer.name}
      statusChecker:
        name: ${self:service}-status-checker-${self:provider.stage}
        arn: arn:aws:states:${self:provider.region}:${ssm:/bamboo-on-teams/accountId}:stateMachine:${self:custom.aws.stepFunction.statusChecker.name}

  prune:
    automatic: true
    number: 3

  serverless-offline:
    noPrependStageInUrl: true

  serverless-offline-ssm:
    stages:
      - bamboo
      - local
    ssm:
      "/bamboo-on-teams/accountId": placeholder
      "/bamboo-on-teams/deploymentBucket": placeholder
      "/bamboo-on-teams/securityGroupId": placeholder
      "/bamboo-on-teams/subnetId": placeholder
      "/bamboo-on-teams/applicationConfig": placeholder

  api:
    urls:
      prefix: /bamboo-on-teams/v1
      command: ${self:custom.api.urls.prefix}/command
